export interface ColorVariant {
  color: string
  colorName: string
  image: string
  additionalImages?: string[]
}

export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  category: "sneakers" | "socks" | "football-tees"
  sizes: string[]
  image: string
  backImage?: string
  colorVariants?: ColorVariant[] // New field for color options
  isFeatured: boolean
  isHotDeal: boolean
  isNewRelease: boolean
}

const newSeasonJerseys: Product[] = [
  // NEW 25/26 ARSENAL HOME JERSEY
  {
    id: 114,
    name: "Arsenal 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/arsenal-2526-home-main.png", // Corrected to .jpeg
    backImage: "/images/jerseys/arsenal-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 AC MILAN HOME JERSEY
  {
    id: 115,
    name: "AC Milan 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/ac-milan-2526-home-front.png",
    backImage: "/images/jerseys/ac-milan-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 CHELSEA JERSEYS
  {
    id: 116,
    name: "Chelsea 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/chelsea-2526-home-main.png",
    backImage: "/images/jerseys/chelsea-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  {
    id: 117,
    name: "Chelsea 25/26 Away Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/chelsea-2526-away-front.png",
    backImage: "/images/jerseys/chelsea-2526-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 BAYERN MUNICH HOME JERSEY
  {
    id: 118,
    name: "Bayern Munich 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bayern-munich-2526-home-front.png",
    backImage: "/images/jerseys/bayern-munich-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 BARCELONA HOME JERSEY
  {
    id: 119,
    name: "FC Barcelona 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/barcelona-2526-home-front.png",
    backImage: "/images/jerseys/barcelona-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 JUVENTUS HOME JERSEY
  {
    id: 120,
    name: "Juventus 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/juventus-2526-home-front.png",
    backImage: "/images/jerseys/juventus-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 MANCHESTER CITY HOME JERSEY
  {
    id: 121,
    name: "Manchester City 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-city-2526-home-front.png",
    backImage: "/images/jerseys/manchester-city-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 MANCHESTER UNITED HOME JERSEY
  {
    id: 122,
    name: "Manchester United 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-united-2526-home-front.png",
    backImage: "/images/jerseys/manchester-united-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 PSG HOME JERSEY
  {
    id: 123,
    name: "Paris Saint-Germain 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/psg-2526-home-front.png",
    backImage: "/images/jerseys/psg-2526-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 REAL MADRID AWAY JERSEY
  {
    id: 124,
    name: "Real Madrid 25/26 Away Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/real-madrid-2526-away-front.png",
    backImage: "/images/jerseys/real-madrid-2526-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 REAL MADRID HOME JERSEY
  {
    id: 125,
    name: "Real Madrid 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/real-madrid-2526-home-main.png",
    backImage: "/images/jerseys/real-madrid-2526-home-back-alt.png",
    additionalImages: [
      "/images/jerseys/real-madrid-2526-home-detail-3.png",
      "/images/jerseys/real-madrid-2526-home-detail-4.png",
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 TOTTENHAM HOME JERSEY
  {
    id: 126,
    name: "Tottenham Hotspur 25/26 Home Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/tottenham-2526-home-main.png",
    backImage: "/images/jerseys/tottenham-2526-home-back-alt.png",
    additionalImages: ["/images/jerseys/tottenham-2526-home-detail-2.png"],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
  // NEW 25/26 TOTTENHAM AWAY JERSEY
  {
    id: 127,
    name: "Tottenham Hotspur 25/26 Away Jersey",
    price: 1600,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/tottenham-2526-away-main.png",
    backImage: "/images/jerseys/tottenham-2526-away-back-alt.png",
    additionalImages: ["/images/jerseys/tottenham-2526-away-detail-2.png"],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: true,
  },
]

const otherProducts: Product[] = [
  // Socks - Updated with real products
  {
    id: 8,
    name: "Jordan Cushioned Crew - White/Red",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/jordan-white-red-crew.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 9,
    name: "Nike Unisex Cushioned Crew - Black/White",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/nike-black-white-crew.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 10,
    name: "Nike Unisex Cushioned Crew - White/Black",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/nike-white-black-crew.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 104,
    name: "Nike Unisex Cushioned Crew - Grey/Black",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/nike-grey-black-crew.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 105,
    name: "Adidas Trefoil Cushioned Crew - White/Black",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/adidas-white-black-crew.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 106,
    name: "Adidas Trefoil Cushioned Crew - Black/White",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/adidas-black-white-crew.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 107,
    name: "Vans Cushioned Crew - White/Black",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/vans-white-black-crew.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 108,
    name: "Vans Cushioned Crew Socks - Black/White",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/vans-black-white-crew.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 109,
    name: "Puma Cushioned Crew Socks - Black/White",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/puma-black-white-crew.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 110,
    name: "Puma Cushioned Crew Socks - White/Black",
    price: 150,
    category: "socks",
    sizes: ["S", "M", "L", "XL"],
    image: "/images/socks/puma-white-black-crew-jordan.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },

  // Football Tees - COMPLETE COLLECTION (24/25 season and older)
  {
    id: 11,
    name: "Arsenal 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/arsenal-2425-home-front.png",
    backImage: "/images/jerseys/arsenal-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 12,
    name: "Arsenal 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/arsenal-2425-away-front.png",
    backImage: "/images/jerseys/arsenal-2425-away-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 13,
    name: "AC Milan 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/ac-milan-2425-home-front.png",
    backImage: "/images/jerseys/ac-milan-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 14,
    name: "AC Milan 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/ac-milan-2425-away-front.png",
    backImage: "/images/jerseys/ac-milan-2425-away-back.png",
    isFeatured: false,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 15,
    name: "Aston Villa 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/aston-villa-2425-home-front.png",
    backImage: "/images/jerseys/aston-villa-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 16,
    name: "Atletico Madrid 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/atletico-madrid-2425-home-front.png",
    backImage: "/images/jerseys/atletico-madrid-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 17,
    name: "Atletico Madrid 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/atletico-madrid-2425-away-front.png",
    backImage: "/images/jerseys/atletico-madrid-2425-away-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 18,
    name: "Borussia Dortmund 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bvb-2425-home-front.png",
    backImage: "/images/jerseys/bvb-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 19,
    name: "Borussia Dortmund 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bvb-2425-away-front.png",
    backImage: "/images/jerseys/bvb-2425-away-back.png",
    isFeatured: false,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 20,
    name: "Chelsea 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/chelsea-2425-away-front.png",
    backImage: "/images/jerseys/chelsea-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 21,
    name: "FC Barcelona 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/barcelona-2425-home-front.png",
    backImage: "/images/jerseys/barcelona-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 22,
    name: "FC Barcelona 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/barcelona-2425-away-front.png",
    backImage: "/images/jerseys/barcelona-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 23,
    name: "FC Barcelona 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/barcelona-2425-third-front.png",
    backImage: "/images/jerseys/barcelona-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 24,
    name: "Chelsea 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/chelsea-2425-home-front.png",
    backImage: "/images/jerseys/chelsea-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 25,
    name: "Chelsea 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/chelsea-2425-third-front.png",
    backImage: "/images/jerseys/chelsea-2425-third-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 26,
    name: "Inter Milan 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/inter-milan-2425-home-front.png",
    backImage: "/images/jerseys/inter-milan-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 27,
    name: "Inter Milan 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/inter-milan-2425-away-front.png",
    backImage: "/images/jerseys/inter-milan-2425-away-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 28,
    name: "Bayern Munich 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bayern-munich-2425-home-front.png",
    backImage: "/images/jerseys/bayern-munich-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 29,
    name: "Bayern Munich 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bayern-munich-2425-away-front.png",
    backImage: "/images/jerseys/bayern-munich-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 30,
    name: "Bayern Munich 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/bayern-munich-2425-third-front.png", // This one is actually PNG
    backImage: "/images/jerseys/bayern-munich-2425-third-back.png", // This one is actually PNG
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 31,
    name: "Inter Milan 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/inter-milan-2425-third-front.png",
    backImage: "/images/jerseys/inter-milan-2425-third-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 32,
    name: "Juventus 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/juventus-2425-home-front.png",
    backImage: "/images/jerseys/juventus-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 33,
    name: "Juventus 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/juventus-2425-away-front.png",
    backImage: "/images/jerseys/juventus-2425-away-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 34,
    name: "Kaizer Chiefs 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/kaizer-chiefs-2425-home-front.png",
    backImage: "/images/jerseys/kaizer-chiefs-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 35,
    name: "Kaizer Chiefs 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/kaizer-chiefs-2425-away-front.png",
    backImage: "/images/jerseys/kaizer-chiefs-2425-away-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 36,
    name: "Liverpool 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/liverpool-2425-home-front.png",
    backImage: "/images/jerseys/liverpool-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 37,
    name: "Liverpool 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/liverpool-2425-away-front.png",
    backImage: "/images/jerseys/liverpool-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 38,
    name: "Liverpool 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/liverpool-2425-third-front.png",
    backImage: "/images/jerseys/liverpool-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 39,
    name: "Manchester City 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-city-2425-home-front.png",
    backImage: "/images/jerseys/manchester-city-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 40,
    name: "Manchester City 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-city-2425-third-front.png",
    backImage: "/images/jerseys/manchester-city-2425-third-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 41,
    name: "Manchester City 24/25 Fourth Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-city-2425-fourth-front.png",
    backImage: "/images/jerseys/manchester-city-2425-fourth-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 42,
    name: "Manchester United 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-united-2425-away-front.png",
    backImage: "/images/jerseys/manchester-united-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 43,
    name: "Manchester United 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-united-2425-home-front.png",
    backImage: "/images/jerseys/manchester-united-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 44,
    name: "Manchester United 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/manchester-united-2425-third-front.png",
    backImage: "/images/jerseys/manchester-united-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 45,
    name: "Newcastle United 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/newcastle-2425-home-front.png",
    backImage: "/images/jerseys/newcastle-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 46,
    name: "Newcastle United 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/newcastle-2425-third-front.png",
    backImage: "/images/jerseys/newcastle-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 47,
    name: "Marseille 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/marseille-2425-home-front.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 48,
    name: "Marseille 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/marseille-2425-away-front.png",
    backImage: "/images/jerseys/marseille-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 49,
    name: "Orlando Pirates 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/orlando-pirates-2425-home-front.png",
    backImage: "/images/jerseys/orlando-pirates-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 50,
    name: "Orlando Pirates 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/orlando-pirates-2425-away-front.png",
    backImage: "/images/jerseys/orlando-pirates-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 51,
    name: "Paris Saint-Germain 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/psg-2425-home-front.png",
    backImage: "/images/jerseys/psg-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 52,
    name: "Paris Saint-Germain 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/psg-2425-away-front.png",
    backImage: "/images/jerseys/psg-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 53,
    name: "Paris Saint-Germain 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/psg-2425-third-front.png",
    backImage: "/images/jerseys/psg-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 54,
    name: "Real Madrid 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/real-madrid-2425-home-front.png",
    backImage: "/images/jerseys/real-madrid-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 55,
    name: "Real Madrid 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/real-madrid-2425-away-front.png",
    backImage: "/images/jerseys/real-madrid-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 56,
    name: "Real Madrid 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/real-madrid-2425-third-front.png",
    backImage: "/images/jerseys/real-madrid-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },
  {
    id: 57,
    name: "RB Leipzig 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/rb-leipzig-2425-home-front.png",
    backImage: "/images/jerseys/rb-leipzig-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 58,
    name: "SSC Napoli 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/napoli-2425-home-front.png",
    backImage: "/images/jerseys/napoli-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 59,
    name: "SSC Napoli 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/napoli-2425-away-front.png",
    backImage: "/images/jerseys/napoli-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 60,
    name: "Tottenham Hotspur 24/25 Home Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/tottenham-2425-home-front.png",
    backImage: "/images/jerseys/tottenham-2425-home-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 61,
    name: "Tottenham Hotspur 24/25 Away Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/tottenham-2425-away-front.png",
    backImage: "/images/jerseys/tottenham-2425-away-back.png",
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 62,
    name: "Tottenham Hotspur 24/25 Third Jersey",
    price: 1500,
    category: "football-tees",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    image: "/images/jerseys/tottenham-2425-third-front.png",
    backImage: "/images/jerseys/tottenham-2425-third-back.png",
    isFeatured: true,
    isHotDeal: false,
    isNewRelease: false,
  },

  // SNEAKERS - Only those with real product images
  {
    id: 63,
    name: "Nike Air Max Plus Drift",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-plus-drift-black-side.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black",
        image: "/images/sneakers/nike-air-max-plus-drift-black-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-drift-black-top.png",
          "/images/sneakers/nike-air-max-plus-drift-black-profile.png",
        ],
      },
      {
        color: "#C0C0C0",
        colorName: "Light Silver/Dark Smoke Grey",
        image: "/images/sneakers/nike-air-max-plus-drift-light-silver-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-drift-light-silver-top.png",
          "/images/sneakers/nike-air-max-plus-drift-light-silver-pair.png",
        ],
      },
      {
        color: "#87CEEB",
        colorName: "Summer White/Light Blue",
        image: "/images/sneakers/nike-air-max-plus-drift-summer-white-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-drift-summer-white-top.png",
          "/images/sneakers/nike-air-max-plus-drift-summer-white-profile.png",
          "/images/sneakers/nike-air-max-plus-drift-summer-white-pair.png",
        ],
      },
      {
        color: "#D3D3D3",
        colorName: "Light Smoke Grey/Multicolor",
        image: "/images/sneakers/nike-air-max-plus-drift-light-smoke-grey-multicolor.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-drift-light-smoke-grey-top.png",
          "/images/sneakers/nike-air-max-plus-drift-multicolor-side.png",
        ],
      },
      {
        color: "#1a1a1a",
        colorName: "Black/White Drift Pattern",
        image: "/images/sneakers/nike-air-max-plus-drift-black-white-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 64,
    name: "Nike Shox TL",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-shox-tl-silver-side.png",
    colorVariants: [
      {
        color: "#C0C0C0",
        colorName: "Metallic Silver/Black/White",
        image: "/images/sneakers/nike-shox-tl-silver-side.png",
        additionalImages: [
          "/images/sneakers/nike-shox-tl-silver-top.png",
          "/images/sneakers/nike-shox-tl-silver-pair.png",
        ],
      },
      {
        color: "#FFFFFF",
        colorName: "White",
        image: "/images/sneakers/nike-shox-tl-white-pair.png",
        additionalImages: [
          "/images/sneakers/nike-shox-tl-white-side.png",
          "/images/sneakers/nike-shox-tl-white-top.png",
        ],
      },
      {
        color: "#000000",
        colorName: "Black",
        image: "/images/sneakers/nike-shox-tl-black-side.png",
        additionalImages: [
          "/images/sneakers/nike-shox-tl-black-top.png",
          "/images/sneakers/nike-shox-tl-black-pair.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 65,
    name: "Air Jordan 1",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-1-black-smoke-grey-top.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/Light Smoke Grey/White",
        image: "/images/sneakers/air-jordan-1-black-smoke-grey-top.png",
        additionalImages: [
          "/images/sneakers/air-jordan-1-black-smoke-grey-pair.png",
          "/images/sneakers/air-jordan-1-black-smoke-grey-side.png",
        ],
      },
      {
        color: "#800080",
        colorName: "Court Purple/White",
        image: "/images/sneakers/air-jordan-1-high-court-purple-pair.png",
        additionalImages: [],
      },
      {
        color: "#006400",
        colorName: "Pine Green/White",
        image: "/images/sneakers/air-jordan-1-high-pine-green.png",
        additionalImages: [],
      },
      {
        color: "#87CEEB",
        colorName: "University Blue/White",
        image: "/images/sneakers/air-jordan-1-high-unc-blue.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 66,
    name: "Nike Air Max DN",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-dn-black-white-side.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/White",
        image: "/images/sneakers/nike-air-max-dn-black-white-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-dn-black-white-top.png",
          "/images/sneakers/nike-air-max-dn-black-white-profile.png",
          "/images/sneakers/nike-air-max-dn-black-white-pair.png",
        ],
      },
      {
        color: "#FFFFFF",
        colorName: "White",
        image: "/images/sneakers/nike-air-max-dn-white-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-dn-white-side.png",
          "/images/sneakers/nike-air-max-dn-white-top.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 67,
    name: "New Balance 9060",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/new-balance-9060-purple-side.png",
    colorVariants: [
      {
        color: "#D8BFD8",
        colorName: "Purple/Cream/Grey",
        image: "/images/sneakers/new-balance-9060-purple-side.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 68,
    name: "Air Jordan 4 Retro",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-university-blue-pair.png",
    colorVariants: [
      {
        color: "#87CEEB",
        colorName: "University Blue/White",
        image: "/images/sneakers/air-jordan-4-university-blue-pair.png",
        additionalImages: [],
      },
      {
        color: "#FFFFFF",
        colorName: "White/Green",
        image: "/images/sneakers/air-jordan-4-retro-white-green.png",
        additionalImages: [],
      },
      {
        color: "#F5F5F5",
        colorName: "White Cement",
        image: "/images/sneakers/air-jordan-4-retro-white-cement.png",
        additionalImages: [],
      },
      {
        color: "#98FB98",
        colorName: "White/Light Green",
        image: "/images/sneakers/air-jordan-4-retro-white-light-green.png",
        additionalImages: [],
      },
      {
        color: "#DDA0DD",
        colorName: "White/Purple",
        image: "/images/sneakers/air-jordan-4-retro-white-purple.png",
        additionalImages: [],
      },
      {
        color: "#000000",
        colorName: "Black Cat",
        image: "/images/sneakers/air-jordan-4-retro-black-cat.png",
        additionalImages: [],
      },
      {
        color: "#FF0000",
        colorName: "White/Fire Red",
        image: "/images/sneakers/air-jordan-4-retro-white-red.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 69,
    name: "Adidas Gazelle Bold",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-gazelle-bold-cream-green-side.png",
    colorVariants: [
      {
        color: "#F5F5DC",
        colorName: "Cream Collegiate/Green",
        image: "/images/sneakers/adidas-gazelle-bold-cream-green-side.png",
        additionalImages: [
          "/images/sneakers/adidas-gazelle-bold-cream-green-pair.png",
          "/images/sneakers/adidas-gazelle-bold-cream-green-top.png",
        ],
      },
      {
        color: "#2F4F4F",
        colorName: "Mineral Green/Putty Grey",
        image: "/images/sneakers/adidas-gazelle-bold-mineral-green-side.png",
        additionalImages: [
          "/images/sneakers/adidas-gazelle-bold-mineral-green-top.png",
          "/images/sneakers/adidas-gazelle-bold-mineral-green-platform.png",
        ],
      },
      {
        color: "#C0C0C0",
        colorName: "Mineral Grey/White",
        image: "/images/sneakers/adidas-gazelle-bold-mineral-grey-white-side.png",
        additionalImages: [
          "/images/sneakers/adidas-gazelle-bold-mineral-grey-white-top.png",
          "/images/sneakers/adidas-gazelle-bold-mineral-grey-white-outsole.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 70,
    name: "Adidas Campus 00s",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-campus-00s-grey-pair.png",
    colorVariants: [
      {
        color: "#808080",
        colorName: "Grey/White",
        image: "/images/sneakers/adidas-campus-00s-grey-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 71,
    name: "Nike Dunk SB Low",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-dunk-sb-low-hemp-green.png",
    colorVariants: [
      {
        color: "#8FBC8F",
        colorName: "Hemp/Green",
        image: "/images/sneakers/nike-dunk-sb-low-hemp-green.png",
        additionalImages: [],
      },
      {
        color: "#F5F5F5",
        colorName: "White/Grey/Green",
        image: "/images/sneakers/nike-dunk-sb-low-white-grey-green.png",
        additionalImages: [],
      },
      {
        color: "#8B4513",
        colorName: "Bandana/Paisley",
        image: "/images/sneakers/nike-dunk-sb-low-bandana-paisley.png",
        additionalImages: [],
      },
      {
        color: "#191970",
        colorName: "Navy/White",
        image: "/images/sneakers/nike-dunk-sb-low-navy-white.png",
        additionalImages: [],
      },
      {
        color: "#FF4500",
        colorName: "Orange",
        image: "/images/sneakers/nike-dunk-sb-low-orange.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 72,
    name: "Air Jordan 1 Low",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-low-1-black-white.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/White",
        image: "/images/sneakers/air-jordan-low-1-black-white.png",
        additionalImages: ["/images/sneakers/air-jordan-low-1-black-white-pair.png"],
      },
      {
        color: "#8B4513",
        colorName: "Brown/White/Pink",
        image: "/images/sneakers/air-jordan-low-1-brown-white-pink.png",
        additionalImages: [],
      },
      {
        color: "#191970",
        colorName: "Navy/White",
        image: "/images/sneakers/air-jordan-low-1-navy-white.png",
        additionalImages: [],
      },
      {
        color: "#FF4500",
        colorName: "Orange/Black/White",
        image: "/images/sneakers/air-jordan-low-1-orange-black-white.png",
        additionalImages: [],
      },
      {
        color: "#D3D3D3",
        colorName: "Light Grey/White",
        image: "/images/sneakers/air-jordan-low-1-light-grey-white.png",
        additionalImages: [],
      },
      {
        color: "#DC143C",
        colorName: "Black/White/Red",
        image: "/images/sneakers/air-jordan-1-low-black-white-red.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 73,
    name: "Adidas Yeezy 450",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-yeezy-450-black.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Cinder",
        image: "/images/sneakers/adidas-yeezy-450-black.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 74,
    name: "Air Jordan 4 Retro 'Bred'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-retro-bred-side.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/Fire Red",
        image: "/images/sneakers/air-jordan-4-retro-bred-side.png",
        additionalImages: [
          "/images/sneakers/air-jordan-4-retro-bred-heel.png",
          "/images/sneakers/air-jordan-4-retro-bred-outsole.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 75,
    name: "Nike Air Force 1 x Stussy",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-force-1-stussy-creamy.png",
    colorVariants: [
      {
        color: "#F5F5DC",
        colorName: "Fossil/Creamy",
        image: "/images/sneakers/nike-air-force-1-stussy-creamy.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 76,
    name: "Nike Dunk Low",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-dunk-low-white-rose-whisper-side.png",
    colorVariants: [
      {
        color: "#FFC0CB",
        colorName: "White/Rose Whisper",
        image: "/images/sneakers/nike-dunk-low-white-rose-whisper-side.png",
        additionalImages: [
          "/images/sneakers/nike-dunk-low-white-rose-whisper-top.png",
          "/images/sneakers/nike-dunk-low-white-rose-whisper-pair.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 78,
    name: "Air Jordan 4 Retro 'Infrared Red'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-retro-infrared-red-side.png",
    colorVariants: [
      {
        color: "#808080",
        colorName: "Cool Grey/Infrared Red",
        image: "/images/sneakers/air-jordan-4-retro-infrared-red-side.png",
        additionalImages: [
          "/images/sneakers/air-jordan-4-retro-infrared-red-pair.png",
          "/images/sneakers/air-jordan-4-retro-infrared-red-heel.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 79,
    name: "New Balance 550",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/new-balance-550-white-purple.png",
    colorVariants: [
      {
        color: "#800080",
        colorName: "White/Purple",
        image: "/images/sneakers/new-balance-550-white-purple.png",
        additionalImages: [],
      },
      {
        color: "#87CEEB",
        colorName: "White/Light Blue",
        image: "/images/sneakers/new-balance-550-white-light-blue.png",
        additionalImages: [],
      },
      {
        color: "#800020",
        colorName: "White/Burgundy",
        image: "/images/sneakers/new-balance-550-white-burgundy.png",
        additionalImages: [],
      },
      {
        color: "#000000",
        colorName: "White/Black",
        image: "/images/sneakers/new-balance-550-white-black.png",
        additionalImages: [],
      },
      {
        color: "#006400",
        colorName: "White/Green",
        image: "/images/sneakers/new-balance-550-white-green.png",
        additionalImages: [],
      },
      {
        color: "#808080",
        colorName: "White/Grey",
        image: "/images/sneakers/new-balance-550-white-grey.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 80,
    name: "Nike Air Force 1 Pixel",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-force-1-pixel-white-side.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White",
        image: "/images/sneakers/nike-air-force-1-pixel-white-side.png",
        additionalImages: ["/images/sneakers/nike-air-force-1-pixel-white-profile.png"],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 81,
    name: "Nike Air Force 1",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-force-1-white.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White",
        image: "/images/sneakers/nike-air-force-1-white.png",
        additionalImages: [],
      },
      {
        color: "#000000",
        colorName: "Black",
        image: "/images/sneakers/nike-air-force-1-black.png",
        additionalImages: [],
      },
      {
        color: "#FF69B4",
        colorName: "White/Pink",
        image: "/images/sneakers/nike-air-force-1-white-pink-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 82,
    name: "Adidas Yeezy Slides",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-yeezy-slides-grey.png",
    colorVariants: [
      {
        color: "#808080",
        colorName: "Grey",
        image: "/images/sneakers/adidas-yeezy-slides-grey.png",
        additionalImages: [],
      },
      {
        color: "#F5F5DC",
        colorName: "Cream/Bone",
        image: "/images/sneakers/adidas-yeezy-foam-runner-cream.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 83,
    name: "Adidas Adilette 22",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-adilette-22-white.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White",
        image: "/images/sneakers/adidas-adilette-22-white.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 84,
    name: "Nike Air Max Portal",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-portal-light-blue-teal-pair.png",
    colorVariants: [
      {
        color: "#87CEEB",
        colorName: "Light Blue/Teal/White",
        image: "/images/sneakers/nike-air-max-portal-light-blue-teal-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-light-blue-teal-side.png",
          "/images/sneakers/nike-air-max-portal-light-blue-teal-top.png",
        ],
      },
      {
        color: "#1E90FF",
        colorName: "Blue/Black/Yellow",
        image: "/images/sneakers/nike-air-max-portal-blue-black-yellow-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-blue-black-yellow-top.png",
          "/images/sneakers/nike-air-max-portal-blue-black-yellow-side.png",
        ],
      },
      {
        color: "#FF4500",
        colorName: "Black/Orange/Red Gradient",
        image: "/images/sneakers/nike-air-max-portal-black-orange-red-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-black-orange-red-side.png",
          "/images/sneakers/nike-air-max-portal-orange-red-gradient-detail.png",
        ],
      },
      {
        color: "#FFB6C1",
        colorName: "Pink/Rose",
        image: "/images/sneakers/nike-air-max-portal-pink-rose-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-pink-rose-side.png",
          "/images/sneakers/nike-air-max-portal-pink-rose-top.png",
        ],
      },
      {
        color: "#000000",
        colorName: "Triple Black",
        image: "/images/sneakers/nike-air-max-portal-triple-black-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-triple-black-side.png",
          "/images/sneakers/nike-air-max-portal-triple-black-top.png",
        ],
      },
      {
        color: "#1a1a1a",
        colorName: "Black/White",
        image: "/images/sneakers/nike-air-max-portal-black-white.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-portal-black-white-top.png",
          "/images/sneakers/nike-air-max-portal-black-white-pair.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 85,
    name: "Nike Air Force 1 '07 LX",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-force-1-07-lx-white-pair.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White/Gold",
        image: "/images/sneakers/nike-air-force-1-07-lx-white-pair.png",
        additionalImages: [
          "/images/sneakers/nike-air-force-1-07-lx-white-side.png",
          "/images/sneakers/nike-air-force-1-07-lx-white-top.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 87,
    name: "Adidas Yeezy Foam Runner",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-yeezy-foam-runner-cream.png",
    colorVariants: [
      {
        color: "#F5F5DC",
        colorName: "Cream",
        image: "/images/sneakers/adidas-yeezy-foam-runner-cream.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 88,
    name: "Converse Run Star Motion",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/converse-run-star-motion-black.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/White",
        image: "/images/sneakers/converse-run-star-motion-black.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 89,
    name: "Nike Air Max Plus TN SE",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-plus-tn-se-black-solar-red-side.png",
    colorVariants: [
      {
        color: "#FF4500",
        colorName: "Black/Solar Red Gradient",
        image: "/images/sneakers/nike-air-max-plus-tn-se-black-solar-red-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-tn-se-black-solar-red-top.png",
          "/images/sneakers/nike-air-max-plus-tn-se-black-solar-red-pair.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 90,
    name: "Air Jordan 4 Retro 'Fire Red'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-retro-fire-red-side.png",
    colorVariants: [
      {
        color: "#DC143C",
        colorName: "White/Fire Red/Black",
        image: "/images/sneakers/air-jordan-4-retro-fire-red-side.png",
        additionalImages: [
          "/images/sneakers/air-jordan-4-retro-fire-red-heel.png",
          "/images/sneakers/air-jordan-4-retro-fire-red-outsole.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 91,
    name: "Air Jordan 4 Retro 'Red Thunder'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-retro-red-thunder-side.png",
    colorVariants: [
      {
        color: "#DC143C",
        colorName: "Black/Red Thunder",
        image: "/images/sneakers/air-jordan-4-retro-red-thunder-side.png",
        additionalImages: [
          "/images/sneakers/air-jordan-4-retro-red-thunder-outsole.png",
          "/images/sneakers/air-jordan-4-retro-red-thunder-heel.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 92,
    name: "Adidas Gazelle Indoor",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-gazelle-indoor-black-white-side.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/White",
        image: "/images/sneakers/adidas-gazelle-indoor-black-white-side.png",
        additionalImages: [
          "/images/sneakers/adidas-gazelle-indoor-black-white-profile.png",
          "/images/sneakers/adidas-gazelle-indoor-black-white-pair.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 93,
    name: "Adidas Yeezy 700 V3 'Alvah'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/adidas-yeezy-700-v3-alvah-pair.png",
    colorVariants: [
      {
        color: "#2F2F2F",
        colorName: "Alvah/Dark Grey",
        image: "/images/sneakers/adidas-yeezy-700-v3-alvah-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 94,
    name: "Nike Air Max Plus",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-plus-white-side.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "Triple White",
        image: "/images/sneakers/nike-air-max-plus-white-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-plus-white-top.png",
          "/images/sneakers/nike-air-max-plus-white-profile.png",
        ],
      },
      {
        color: "#000000",
        colorName: "Black/White Drift",
        image: "/images/sneakers/nike-air-max-plus-drift-black-white-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 95,
    name: "Nike Air Force 1 'Ropes'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-force-1-ropes-white-pair.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White/Rope Laces",
        image: "/images/sneakers/nike-air-force-1-ropes-white-pair.png",
        additionalImages: [],
      },
      {
        color: "#000000",
        colorName: "Black/Rope Laces",
        image: "/images/sneakers/nike-air-force-1-ropes-black-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 96,
    name: "Nike Air More Uptempo",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-uptempo-white-side.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White/Black",
        image: "/images/sneakers/nike-air-uptempo-white-side.png",
        additionalImages: ["/images/sneakers/nike-air-uptempo-white-pair.png"],
      },
      {
        color: "#D2B48C",
        colorName: "Tan/Blue Accents",
        image: "/images/sneakers/nike-air-uptempo-tan-blue-pair.png",
        additionalImages: ["/images/sneakers/nike-air-uptempo-tan-blue-side.png"],
      },
      {
        color: "#000000",
        colorName: "Black/White",
        image: "/images/sneakers/nike-air-uptempo-black-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 101,
    name: "Nike SB Dunk Low",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-dunk-sb-low-black-white-panda-side.png",
    colorVariants: [
      {
        color: "#000000",
        colorName: "Black/White Panda",
        image: "/images/sneakers/nike-dunk-sb-low-black-white-panda-side.png",
        additionalImages: [],
      },
      {
        color: "#D2B48C",
        colorName: "Tan/White",
        image: "/images/sneakers/nike-dunk-sb-low-tan-white-side.png",
        additionalImages: [],
      },
      {
        color: "#D3D3D3",
        colorName: "Light Grey/White",
        image: "/images/sneakers/nike-dunk-sb-low-light-grey-white-side.png",
        additionalImages: [],
      },
      {
        color: "#006400",
        colorName: "Green/White",
        image: "/images/sneakers/nike-dunk-sb-low-green-white-side.png",
        additionalImages: [],
      },
      {
        color: "#FF4500",
        colorName: "Orange/White",
        image: "/images/sneakers/nike-dunk-sb-low-orange-white-side.png",
        additionalImages: [],
      },
      {
        color: "#808080",
        colorName: "Grey/Translucent Sole",
        image: "/images/sneakers/nike-dunk-sb-low-grey-translucent-side.png",
        additionalImages: [],
      },
      {
        color: "#DC143C",
        colorName: "University Red/White",
        image: "/images/sneakers/nike-dunk-sb-low-university-red-white-side.png",
        additionalImages: [],
      },
      {
        color: "#87CEEB",
        colorName: "University Blue/White",
        image: "/images/sneakers/nike-dunk-sb-low-university-blue-white-side.png",
        additionalImages: [],
      },
      {
        color: "#228B22",
        colorName: "Pine Green/White",
        image: "/images/sneakers/nike-dunk-sb-low-pine-green-white-side.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 102,
    name: "Air Jordan 4 Retro 'Cool Grey'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/air-jordan-4-retro-cool-grey-pair.png",
    colorVariants: [
      {
        color: "#808080",
        colorName: "Cool Grey/Chrome",
        image: "/images/sneakers/air-jordan-4-retro-cool-grey-pair.png",
        additionalImages: ["/images/sneakers/air-jordan-4-retro-cool-grey-heel.png"],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 103,
    name: "Nike Dunk Low 'Shashiko'",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-dunk-low-shashiko-navy-white-pair.png",
    colorVariants: [
      {
        color: "#1e3a8a",
        colorName: "Navy/White Shashiko",
        image: "/images/sneakers/nike-dunk-low-shashiko-navy-white-pair.png",
        additionalImages: [],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 112,
    name: "Puma 180",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/puma-180-green-black-pair.png",
    colorVariants: [
      {
        color: "#006400",
        colorName: "Green/Black",
        image: "/images/sneakers/puma-180-green-black-pair.png",
        additionalImages: [
          "/images/sneakers/puma-180-green-black-side.png",
          "/images/sneakers/puma-180-green-black-heel.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
  {
    id: 113,
    name: "Nike Air Max 1",
    price: 1500,
    category: "sneakers",
    sizes: ["UK 3", "UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"],
    image: "/images/sneakers/nike-air-max-1-white-platinum-black-side.png",
    colorVariants: [
      {
        color: "#FFFFFF",
        colorName: "White/Pure Platinum/Black",
        image: "/images/sneakers/nike-air-max-1-white-platinum-black-side.png",
        additionalImages: [
          "/images/sneakers/nike-air-max-1-white-platinum-black-pair.png",
          "/images/sneakers/nike-air-max-1-white-platinum-black-top.png",
        ],
      },
    ],
    isFeatured: true,
    isHotDeal: true,
    isNewRelease: false,
  },
]

export const products: Product[] = [...newSeasonJerseys, ...otherProducts]
